language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; assembly'
after_script:
- ci/sbt-deploy.sh
- rm -rf ci
env:
  global:
    secure: crMQyJbG6tmKFoSV0WhVXY0h95CLdgAw5fGJx4xDWkeXvIbyr117bemPiRDv+t7DXxaqMqptmGyvI460hZ08c9l2VcavhYtwE7NVy2WVjUqHrI+7+gG3iPMWY7AUkmopaH3JSlJlKTKg6Ya7vKHTkv/dcSQGSF4Co3LJ9hFxXns=
