language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; assembly' && ci/sbt-deploy.sh
  && ci/sbt-gh-pages-ssh.sh
after_script:
- rm -rf ci
env:
  global:
    secure: SNCyfM1DA7kaT57Vm7kaiEfC7etjxWOWa8llbNY6ffJnSY+OQer25lo+vm63TldtDyNZ513fBj7XmbgE2SxfTsvQpKs1X8YtuonBBDXVGRY6eNo3EBtqKgX3nHdIvHVwUsuKvpksFHxlKLFmnP68sNdwnf8DaXoTttt9QRUYVmY=
before_install:
- openssl aes-256-cbc -K $encrypted_a7cf6d2ecbdf_key -iv $encrypted_a7cf6d2ecbdf_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key.pem -d
